# Generated by Django 3.1.5 on 2021-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210126_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='haha', max_length=255),
            preserve_default=False,
        ),
    ]
